### ISSUE TITLE
I want to be able to get App version

### ISSUE THREAD

**Issue by kostiakoval** [zenangst/Versions#11]
``` swift
let version = App.version
```

**Comment by zenangst** [comment]
@kostiakoval How would you like that to work? Add a static class called `App` that has a calculated version property that returns the version of the current application?

**Comment by zenangst** [comment]
@kostiakoval https://github.com/zenangst/Versions/pull/12

This is what I have so far, was it something like this that you had in mind?

**Comment by kostiakoval** [comment]
yes, maybe just small adjustment in the implementation details
