### ISSUE TITLE
Swift space style

### ISSUE THREAD

**Issue by kostiakoval** [zenangst/Versions#7]
I love to use 2 space style. First I've tried it with ReactiveCocoa, it looks a bit better when you have nested code blocks with 2 space distance.

In swift names and methods are shorter and nicer, and I like more to have 2 space distance.
Based on this https://github.com/raywenderlich/swift-style-guide

**Comment by zenangst** [comment]
I like 2 spaces :)

**Comment by kostiakoval** [comment]
Great . you can change it in Xcode setting and do (cmd+ A, cmd + I ) select all and adjust spaces.

**Comment by zenangst** [comment]
Made a pull request for this https://github.com/zenangst/Versions/pull/9

**Comment by kostiakoval** [comment]
Closing this one.
